language: cpp
before_script:
- cd fresh
before_install:
- sudo apt-get -qq update
- sudo apt-get -qq install cmake p7zip-full build-essential libsdl1.2-dev libsdl-mixer1.2-dev libsdl-mixer1.2 sshpass
- mkdir libs
- cd libs
- wget http://ffmpeg.zeranoe.com/builds/win32/dev/ffmpeg-2.1.3-win32-dev.7z
- /usr/bin/7za x ffmpeg-2.1.3-win32-dev.7z
- mv ffmpeg-2.1.3-win32-dev ffmpeg-dev
- wget http://mirror.ufs.ac.za/gnuwin32/freetype/2.3.5-1/freetype-2.3.5-1-lib.zip
- unzip freetype-2.3.5-1-lib.zip -d freetype
- wget http://www.libsdl.org/release/SDL-devel-1.2.15-mingw32.tar.gz
- tar xfz SDL-devel-1.2.15-mingw32.tar.gz
- sudo cp SDL-1.2.15/bin/* /usr/i586-mingw32msvc/bin/
- sudo cp -r SDL-1.2.15/include/SDL/* /usr/i586-mingw32msvc/include/
- sudo cp SDL-1.2.15/lib/* /usr/i586-mingw32msvc/lib/
- sudo chmod +x /usr/i586-mingw32msvc/bin/sdl-config
- wget http://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-devel-1.2.12-VC.zip
- unzip SDL_mixer-devel-1.2.12-VC.zip
- sudo cp -r SDL_mixer-1.2.12/include/* /usr/i586-mingw32msvc/include/
- sudo cp SDL_mixer-1.2.12/lib/x86/* /usr/i586-mingw32msvc/lib/
- mkdir lua
- wget http://skylink.dl.sourceforge.net/project/mingw/MinGW/Extension/lua/lua-5.1.4-4/lua-5.1.4-4-mingw32-dll-51.tar.xz
- tar xJf lua-5.1.4-4-mingw32-dll-51.tar.xz -C lua
- wget http://netcologne.dl.sourceforge.net/project/mingw/MinGW/Extension/lua/lua-5.1.4-4/lua-5.1.4-4-mingw32-dev.tar.xz
- tar xJf lua-5.1.4-4-mingw32-dev.tar.xz -C lua
after_success:
- cd $TRAVIS_BUILD_DIR
- mkdir -p fresh/CorsixTH
- cp libs/SDL-1.2.15/bin/SDL.dll fresh/CorsixTH/
- cp libs/SDL_mixer-1.2.12/lib/x86/SDL_mixer.dll fresh/CorsixTH/
- cd CorsixTH/
- cp -r * ../fresh/CorsixTH/
- cd ../fresh
- mv CorsixTH.exe CorsixTH/
- cd CorsixTH
- zip CTH-$TRAVIS_COMMIT.zip *
- sshpass -p "$SCP_PASS" scp -v -P12349 cthbuilder@server2.armedpineapple.co.uk:/builds/ CTH-$TRAVIS_COMMIT.zip
- cat CMakeCache.txt
install:
- cd $TRAVIS_BUILD_DIR
- cmake -DCMAKE_TOOLCHAIN_FILE=build_files/toolchain-mingw.cmake -DWITH_AUDIO=ON -DWITH_MOVIES=OFF -DSDL_LIBRARY=$TRAVIS_BUILD_DIR/libs/SDL-1.2.15/lib/libSDL.dll.a -DSDL_INCLUDE_DIR=libs/SDL-1.2.15/include/SDL -DSDLMAIN_LIBRARY=libs/SDL-1.2.15/lib/libSDLmain.a -DSDLMIXER_INCLUDE_DIR=libs/SDL_mixer-1.2.12/include -DSDLMIXER_LIBRARY=libs/SDL_mixer-1.2.12/lib/x86/SDL_mixer.lib -DLUA_LIBRARY=libs/lua/lib/liblua.dll.a -DLUA_INCLUDE_DIR=libs/lua/include -DFREETYPE_INCLUDE_DIR_freetype2=libs/freetype/include/freetype2 -DFREETYPE_INCLUDE_DIR_ft2build=libs/freetype/include -DFREETYPE_LIBRARY=libs/freetype/lib/libfreetype.dll.a -Bfresh -H. --debug-output
script: make
env:
  global:
    secure: "SnQve7CSWXvEMOoJI4rJnO0OC5bPEhwOScUNBpbsPDMCa5DKBUDJALgRSGZYBriOxIVAxqh/W6Y3twa5QkRECJnyNEppK/5vXQxRyNEhmMZaqgaqeg85FrYvn866Qp7YeVy+Xbth3Jay7uRB/eXh+gaaVtlxBc9cX57K1ls6aJg="
