language: cpp

before_install:
 - sudo apt-get -qq update
 - sudo apt-get -qq install cmake p7zip
 - mkdir ~/libs
 - cd ~/libs
 - wget http://ffmpeg.zeranoe.com/builds/win32/dev/ffmpeg-2.1.3-win32-dev.7z 
 - /usr/bin/7za x ffmpeg-2.1.3-win32-dev.7z
 - mv ffmpeg-2.1.3-win32-dev ffmpeg-dev
 - wget http://mirror.ufs.ac.za/gnuwin32/freetype/2.3.5-1/freetype-2.3.5-1-lib.zip
 - unzip freetype-2.3.5-1-lib.zip -d freetype
 - wget http://www.libsdl.org/release/SDL-devel-1.2.15-mingw32.tar.gz
 - tar xfz SDL-devel-1.2.15-mingw32.tar.gz
 - wget http://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-devel-1.2.12-VC.zip
 - unzip SDL_mixer-devel-1.2.12-VC.zip
 
install:
 - cd $TRAVIS_BUILD_DIR
 - cmake -DCMAKE_TOOLCHAIN_FILE=build_files/toolchain-mingw.cmake 
 

 
 
 